---
title: "Group project text part 1"
author: "Alisha Husain"
date: "January 25, 2019"
output: html_document
---


## Part 1 - Understanding The Data 

Cities like Beijing and Shanghai are included in the list of provinces in this dataset because they are municipalities. In China, a municipality is a "city"[^1] with "provincial" power under the unified jurisdiction of the central government. This means that Beijing and Shanghai are considered both cities and provinces. Furthermore, there are a few locations excluded in this dataset that some viewers might argue are "missing". For example, the People's Republic of China claims Taiwan and its surrounding islets as "Taiwan Province", even though Taiwan has been independent from China since 1949. If someone were interested in finding economic statistical information about Taiwan, they would have to visit the website on National Statistics for the Republic of China (Taiwan). Another province that has a large amount of economic data missing from this dataset is the Tibet province; Tibet has been occupied by China since 1965, when it established the "Tibetan Autonomous Region". From our dataset, it is evident that regular reporting of enterprise and output about this region only became available after China's establishment of the TAR. 


[^1]: From Wikipedia - A municipality is often not a "city" in the usual sense of the term (i.e., a large continuous urban settlement), but instead an administrative unit of sorts. 

There are several problems with Chinese statistics that cause unreliability and uncertainty. The first problem is that when China began its major economic transformation in the late 1970s, changing from a command economy to a market economy, the transformation happened faster than China's National Bureau of Statistics had prepared itself for. The result was a major challenge in collecting measurements, because many of these new private service-sector businesses did not report their activity directly to the NBS until the 1990s. This means that the period of 1970-1990 is less reliable for China's economic data. Another issue is that in 1993, China changed its methods of calculating its GDP to the United Nations' standards - however, these concepts were very new to the statisticians in China and would take time to adopt. The challenge of overhauling the country's statistical system makes accurately measuring growth during the transition period unlikely. [Source] (https://www.stlouisfed.org/publications/regional-economist/second-quarter-2017/chinas-economic-data-an-accurate-reflection-or-just-smoke-and-mirrors)

Furthermore, additional  [sources] (https://www.forbes.com/sites/unicefusa/2019/01/23/a-step-closer-to-adulthood-along-a-cold-highway/#7aec101a1632) argue that "there are enormous discrepancies both within NBSC data and then when comparing it to outside data. These discrepancies come from both poor quality statistical management but also unquestionably data manipulation". Critics have offered several recommendations to help fight data falsification at the provincial and individual levels. These include recommendations to introduce measures to check the quality of data collection, corrections for exaggeration, better methodology, and improving timeliness and periodicity of data releases. 
